<a href="https://colab.research.google.com/github/ybaris/DATA-690-WANG/blob/master/Assignment_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 03
The Problem:
Write a program that generates 100 random integers between 0 and 9.

Print them in a 10 by 10 matrix neatly arranged like the following (one space between each number):
- 5 1 5 6 2 7 8 6 4 2 
- 2 3 7 0 6 9 2 4 2 8 
- 0 0 8 6 4 1 7 2 7 6 
- 0 1 9 0 0 8 5 8 6 8 
- 4 1 0 5 5 7 4 6 4 4 
- 6 0 2 0 1 9 8 2 3 9 
- 4 0 4 8 1 7 6 6 2 1 
- 1 7 6 8 5 4 1 9 6 7 
- 6 4 7 9 9 3 8 2 6 1 
- 9 0 6 4 0 1 0 6 9 9 

If the random number is an odd number, print "@" instead. like the following:
- @ @ 0 2 6 @ 8 8 0 0 
- @ 4 @ 4 4 @ 2 @ 2 2 
- @ 6 8 @ @ @ 0 @ 0 @ 
- 2 6 @ 0 @ 2 @ @ 0 @ 
- 8 4 @ @ @ 0 @ @ 6 @ 
- @ @ 4 6 @ @ @ 2 @ 2 
- @ @ @ @ 4 @ @ 2 2 0 
- @ 6 @ 0 0 8 @ 2 0 @ 
- 8 8 @ @ @ 0 0 @ 4 6 
- @ 2 2 6 8 2 @ @ @ 6

Calculate and Print the total of each row like the following (use "*" to separate the total from the numbers):
- 7 6 5 8 8 0 7 6 0 1 * 48 
- 8 5 7 9 8 0 9 3 0 1 * 50 
- 4 0 3 5 3 9 0 8 3 9 * 44 
- 3 5 5 3 8 3 4 3 2 2 * 38 
- 7 7 4 1 2 7 2 3 0 8 * 41 
- 3 9 7 7 0 9 4 0 6 5 * 50 
- 1 9 7 1 3 0 0 1 4 5 * 31 
- 4 4 0 6 7 4 5 6 9 3 * 48 
- 2 1 1 4 2 0 1 2 9 2 * 24
- 2 1 6 7 7 8 1 0 0 4 * 36

Optional: Surround the matrix with asterisks (*) like the following:
***********************
* 5 1 5 6 2 7 8 6 4 2 *
* 2 3 7 0 6 9 2 4 2 8 *
* 0 0 8 6 4 1 7 2 7 6 *
* 0 1 9 0 0 8 5 8 6 8 *
* 4 1 0 5 5 7 4 6 4 4 *
* 6 0 2 0 1 9 8 2 3 9 *
* 4 0 4 8 1 7 6 6 2 1 *
* 1 7 6 8 5 4 1 9 6 7 *
* 6 4 7 9 9 3 8 2 6 1 *
* 9 0 6 4 0 1 0 6 9 9 *
***********************
- The Requirements:
You should program and test the solution in Jupyter notebook:
- Save/upload the notebook file to your GitHub repository
- Submit the link of your GitHub repo to BB.
** Hints:
- You can use Python standard library random to generate one random number at a time
- Alternatively you can use NumPy random library to generate 10 numbers at a time or 100 random number altogether in one shot.
- You are likely to use nested loop - a loop within in another loop since you are dealing with a 10 x 10 matrix.
- You will use modular operator (%) to determine if an integer is an odd number or an even number.
- Use the "end=" option of the print() function to avoid a new line after the print and also to add additional spaces.
for example, print(9, end=" ") will print 9 followed by three spaces and not starting a new line.
- Think through the logic. Try simple things first. Don't make it too complicated. You only need a few lines of code.

# @Riza

In [2]:
import numpy as np

A = np.random.randint(10, size=(10,10))

print("*"*10 + " Task#1 " + "*"*10)
for row in A:
  for element in row:
    print(element, end=" ")
  print("*\n")


print("*"*10 + " Task#2 " + "*"*10)
for row in A:
  for element in row:
    if element % 2 == 1:
      print("@", end=" ")
    else:
      print(element, end=" ")
  print("*\n")


print("*"*10 + " Task#3 " + "*"*10)
for row in A:
  for element in row:
    print(element, end=" ")
  print(f"* {sum(row)}\n")

********** Task#1 **********
3 7 7 1 2 9 7 2 3 9 *

6 1 9 3 3 9 1 2 3 6 *

5 0 3 4 0 9 5 2 3 7 *

6 6 4 3 5 6 6 4 0 7 *

4 8 2 8 6 3 1 8 9 1 *

8 1 7 6 8 0 0 8 5 0 *

2 4 5 7 5 6 5 2 1 4 *

9 0 8 3 6 8 5 9 3 9 *

0 4 0 3 5 9 5 0 4 2 *

4 3 8 9 5 8 5 6 7 3 *

********** Task#2 **********
@ @ @ @ 2 @ @ 2 @ @ *

6 @ @ @ @ @ @ 2 @ 6 *

@ 0 @ 4 0 @ @ 2 @ @ *

6 6 4 @ @ 6 6 4 0 @ *

4 8 2 8 6 @ @ 8 @ @ *

8 @ @ 6 8 0 0 8 @ 0 *

2 4 @ @ @ 6 @ 2 @ 4 *

@ 0 8 @ 6 8 @ @ @ @ *

0 4 0 @ @ @ @ 0 4 2 *

4 @ 8 @ @ 8 @ 6 @ @ *

********** Task#3 **********
3 7 7 1 2 9 7 2 3 9 * 50

6 1 9 3 3 9 1 2 3 6 * 43

5 0 3 4 0 9 5 2 3 7 * 38

6 6 4 3 5 6 6 4 0 7 * 47

4 8 2 8 6 3 1 8 9 1 * 50

8 1 7 6 8 0 0 8 5 0 * 43

2 4 5 7 5 6 5 2 1 4 * 41

9 0 8 3 6 8 5 9 3 9 * 60

0 4 0 3 5 9 5 0 4 2 * 32

4 3 8 9 5 8 5 6 7 3 * 58



# @Baris

In [ ]:
import numpy as np

A = np.random.randint(10, size=(10,10))

print(A)

[[8 6 7 6 9 9 9 4 0 5]
 [2 9 6 7 0 4 6 4 9 2]
 [8 2 6 7 5 7 8 7 4 9]
 [5 6 1 1 3 3 0 3 0 2]
 [7 1 4 0 2 9 7 8 8 3]
 [8 0 9 5 7 0 3 1 7 9]
 [2 4 1 1 1 8 4 0 8 5]
 [1 8 7 5 8 7 3 0 4 5]
 [1 5 7 2 9 6 1 0 1 6]
 [3 9 6 7 5 4 6 3 4 6]]


In [ ]:
for i in A: 
   if i.all() % 2 == 1:
      i == "@"

print(A)

[[8 6 7 6 9 9 9 4 0 5]
 [2 9 6 7 0 4 6 4 9 2]
 [8 2 6 7 5 7 8 7 4 9]
 [5 6 1 1 3 3 0 3 0 2]
 [7 1 4 0 2 9 7 8 8 3]
 [8 0 9 5 7 0 3 1 7 9]
 [2 4 1 1 1 8 4 0 8 5]
 [1 8 7 5 8 7 3 0 4 5]
 [1 5 7 2 9 6 1 0 1 6]
 [3 9 6 7 5 4 6 3 4 6]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  This is separate from the ipykernel package so we can avoid doing imports until


pasta
sandwich


2